export default function blog() {
  return (
    <div className="flex flex-col gap-5">
      <p className="border-l-2 border-brandRed pl-3">
        <i>
          Which Southeast Asian country is the largest producer of energy? What
          are the region&rsquo;s plans to transit to renewable energy and will
          it succeed? Join ABYA&rsquo;s team of writers as we scour the internet
          for &lsquo;expert&rsquo; views -- <strong>Kidding</strong>, we rode on
          the coattails of all hyperlinks you can find below. This article is
          intended to be informative and provide ABYA youth readers an overview
          about our region&rsquo;s latest energy transitions.
        </i>
      </p>
      <p>
        In 2020, this country alone produced 2,773 TWh of energy, accounting for
        about 40% of Southeast Asia&rsquo;s total energy production. Each year,
        it produces more energy than Russia (1130 TWh), Germany (656TWh) and
        France (652TWh) combined-- equivalent to the amount of energy that could
        power an airplane ride from New York to London, 14,000 times. In this
        article, we look at some of Indonesia&rsquo;s latest carbon
        announcements, and discuss how its transition is pivotal to green energy
        access across the rest of Southeast Asia.
      </p>
      <p>
        At the G20 Summit in November 2022, Indonesia launched the most
        ambitious energy transition programme in its history, the Just Energy
        Transition Partnership (JETP)[1] , calling for renewable energy to
        comprise 34% of its power generated by 2030. The JETP will see the
        private sector, as well as member states of the{" "}
        <a href="https://www.edelmanglobaladvisory.com/us-20-billion-investment-deal-indonesias-energy-transition">
          International Partners Group
        </a>{" "}
        provide financial and technical assistance towards enabling the US$20
        billion transition to green energy, over the next 3 to 5 years.
        Alongside international efforts to support Indonesia&rsquo;s transition
        to green energy are its domestic{" "}
        <a href="https://www.aseanbriefing.com/news/indonesias-just-energy-transition-partnership/">
          priorities
        </a>{" "}
        to retire 15 gigawatts of coal power generation over the next three
        decades, create the world&rsquo;s largest green industrial park, and its{" "}
        <a href="https://www.weforum.org/agenda/2023/02/moving-indonesia-the-multi-stakeholder-network-building-indonesia-s-ev-production-market/">
          commitment
        </a>{" "}
        to produce 15.2 million electric motorbikes and cars combined, by 2030.
      </p>
      <p>
        With its vast potential for renewable energy exports, such as
        hydropower, geothermal and solar power, Indonesia stands to not only
        export renewable energy -- but also holds the key to producing the very
        right to emit-- Renewable Energy Certificates (RECs). RECs are tradable
        certificates that represent the generation of one megawatt hour (Mwh) of
        renewable energy. These are used to track the environmental attributes
        of renewable energy, such as the amount of greenhouse gas emissions
        avoided. In the absence of an expert, we at ABYA asked Google&rsquo;s{" "}
        <strong>Bard</strong> what it thinks about how Indonesia&rsquo;s
        renewable energy sector could be impacted by Singapore&rsquo;s latest
        announcement to increase its carbon tax.
      </p>
      <p>
        <strong>Bard</strong> explains that alongside Indonesia&rsquo;s
        announcement of its green transition is that of Singapore&rsquo;s{" "}
        <a href="https://www.nccs.gov.sg/singapores-climate-action/mitigation-efforts/carbontax/">
          plans
        </a>{" "}
        to increase its carbon tax from current levels of S$5/tCO2e, to
        S$25/tCO2e in 2024 and 2025, with a view to reach S$50-S$80/tCO2e by
        2030. The introduction of Singapore&rsquo;s carbon tax is likely to have
        a significant impact on renewable energy trading in the region. The tax
        will make it more expensive to generate electricity from fossil fuels,
        which makes renewable energy more competitive. As a major producer of
        renewable energy, Indonesia has the potential to export RECs to
        Singapore, and other countries in the region.
      </p>
      <p>
        We&rsquo;ve heard enough from <strong>Bard</strong>. Other
        &lsquo;experts&rsquo; that ABYA gathered found that, according to{" "}
        <strong>Reuters</strong>, Singapore and Indonesia{" "}
        <a href="https://www.reuters.com/article/singapore-indonesia-renewables-idUKL1N35O0UZ">
          announced
        </a>{" "}
        joint plans in March 2023, to develop a renewable energy industry in
        Batam, that will produce equipment and build power plants to supply
        electricity into Indonesia for export. Singapore&rsquo;s{" "}
        <strong>National Climate Change Secretariat</strong> also reports that
        Singapore and Indonesia (alongside its other partners) have signed an{" "}
        <a href="https://www.nccs.gov.sg/singapores-climate-action/mitigation-efforts/internationalcollaboration/">
          MOU on carbon credits collaboration
        </a>
        , as well as a small-scale trial import of renewable electricity of{" "}
        <a href="https://www.ema.gov.sg/electricity-imports.aspx">
          100 MW from a solar farm in Pulau Bulan, Indonesia
        </a>
        . Indonesia&rsquo;s transition to green-energy, not if but when it
        succeeds, will mark a paradigm shift from business as usual across
        Southeast Asia. As{" "}
        <span className="underline">
          <strong>
            <a href="https://asia.nikkei.com/Opinion/Indonesia-s-green-energy-transition-is-serious-business">
              Nikkei Asia
            </a>
          </strong>
        </span>{" "}
        puts it, the time to look at Indonesia&rsquo;s energy potential is now.
      </p>
      <p>
        [1] At the G20 leaders' summit in Bali, also in November, Indonesia's
        JETP deal was announced: USD 20 billion in finance over 3 to 5 years,
        half from the donors and half due from the private sector. This
        partnership is co-led by Japan, along with the United Kingdom, Germany,
        France, Canada, Italy, Norway and Denmark. The JETP laid out an
        emissions trajectory for the country and how to achieve it: peaking
        power sector emissions by 2030, and capping carbon dioxide emissions
        levels about a quarter lower than previously expected by the same time.
        Source:{" "}
        <a href="https://www.iisd.org/articles/insight/just-energy-transition-partnerships">
          https://www.iisd.org/articles/insight/just-energy-transition-partnerships
        </a>
      </p>
    </div>
  );
}
